import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiNodedotjs,
  SiPostgresql,
  SiDocker,
  SiTailwindcss,
  SiMongodb,
  SiRedis,
  SiGit,
  SiGithub,
  SiVercel,
  SiFastapi,
  SiFirebase,
  SiPrisma,
  SiPytorch,
  SiOpencv,
  SiNumpy,
  SiPandas,
  SiScikitlearn,
  SiFlutter,
  SiDart,
  SiKotlin,
  SiPhp,
  SiLaravel,
  SiAngular,
  SiVuedotjs,
  SiMysql,
  SiExpress,
  SiNestjs,
  SiSpringboot,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiPostman,
  SiFigma,
  SiAndroidstudio,
  SiSqlite,
  SiApachespark,
  SiClaude,
  SiGithubcopilot,
  SiOpenai,
} from "react-icons/si";
import { FaJava, FaCode, FaMousePointer } from "react-icons/fa";
import { skills as groups } from "@/data/skills";
export interface Skill {
  name: string;
  icon: IconType;
  color: string;
}
const icons: Record<string, IconType> = {
  Cursor: FaMousePointer,
  "Claude Code": SiClaude,
  "GitHub Copilot": SiGithubcopilot,
  Codex: SiOpenai,
  React: SiReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Python: SiPython,
  Java: FaJava,
  "Node.js": SiNodedotjs,
  PostgreSQL: SiPostgresql,
  Docker: SiDocker,
  "Tailwind CSS": SiTailwindcss,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  "Git & GitHub": SiGit,
  "GitHub Actions": SiGithub,
  Vercel: SiVercel,
  FastAPI: SiFastapi,
  Firebase: SiFirebase,
  "Prisma ORM": SiPrisma,
  PyTorch: SiPytorch,
  OpenCV: SiOpencv,
  NumPy: SiNumpy,
  Pandas: SiPandas,
  "Scikit-learn": SiScikitlearn,
  Flutter: SiFlutter,
  Dart: SiDart,
  Kotlin: SiKotlin,
  PHP: SiPhp,
  Laravel: SiLaravel,
  Angular: SiAngular,
  "Vue.js": SiVuedotjs,
  MySQL: SiMysql,
  Express: SiExpress,
  NestJS: SiNestjs,
  "Spring Boot": SiSpringboot,
  HTML: SiHtml5,
  CSS: SiCss3,
  Bootstrap: SiBootstrap,
  Postman: SiPostman,
  Figma: SiFigma,
  "Android Studio": SiAndroidstudio,
  SQLite: SiSqlite,
  "Apache Spark": SiApachespark,
};
const colors = [
  "#61dafb",
  "#ffffff",
  "#3178c6",
  "#f7df1e",
  "#a78bfa",
  "#ff8c00",
  "#5fa04e",
  "#38bdf8",
];
export const skills: Skill[] = groups
  .flatMap((group) => group.items)
  .map((name, index) => ({
    name,
    icon: icons[name] ?? FaCode,
    color: colors[index % colors.length],
  }));
